server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot
          app: smart-spring
          env: dev
          log_type: application
          __path__: /var/log/springboot/smartspring.log

    pipeline_stages:
      - regex:
          expression: '^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\s+\[.*?\]\s+(?P<level>INFO|WARN|ERROR|DEBUG|TRACE)\s+'
      - labels:
          level:
      - output:
          source: level

  - job_name: springboot-email-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot
          app: smart-spring
          env: dev
          log_type: email
          __path__: /var/log/springboot/debug-email.log

    pipeline_stages:
      - regex:
          expression: '^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\s+(?P<level>INFO|WARN|ERROR|DEBUG|TRACE)\s+'
      - labels:
          level:
